version: '3.5'
services:
  superkassa-service:
    container_name: superkasa-service
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/sk_example_db

  db:
    image: postgres:15-alpine
    container_name: sk_example_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sk_example_db
      POSTGRES_USER: sk_example_user
      POSTGRES_PASSWORD: root